name: Next.js CI

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [lts/*]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"

      - name: Install dependencies (Next.js)
        run: yarn install --immutable

      - name: Check Code Format
        run: npm run format:check

      - name: Run Next.js lint
        run: yarn next:lint --max-warnings=0
        working-directory: ./packages/nextjs

      - name: Check typings on Next.js
        run: yarn next:check-types
        working-directory: ./packages/nextjs

      - name: Build Next.js project
        run: yarn build
